# Docker Compose override for development
# This file is automatically loaded by docker-compose
# Use: docker-compose up -d for development with hot reload

version: '3.8'

services:
  backend:
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend:/app
      - /app/venv  # Exclude venv from bind mount
    command: [
      "sh", "-c",
      "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ]

  frontend:
    environment:
      - VITE_DEV_MODE=true
      - VITE_DEBUG_MODE=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - /app/node_modules  # Exclude node_modules from bind mount
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "5173:80"  # Use Vite's default port for development